/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsRosterRouteImport } from './routes/tools/roster'
import { Route as ToolsCharacterLookupRouteImport } from './routes/tools/character-lookup'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRosterRoute = ToolsRosterRouteImport.update({
  id: '/tools/roster',
  path: '/tools/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCharacterLookupRoute = ToolsCharacterLookupRouteImport.update({
  id: '/tools/character-lookup',
  path: '/tools/character-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/character-lookup': typeof ToolsCharacterLookupRoute
  '/tools/roster': typeof ToolsRosterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/character-lookup': typeof ToolsCharacterLookupRoute
  '/tools/roster': typeof ToolsRosterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/character-lookup': typeof ToolsCharacterLookupRoute
  '/tools/roster': typeof ToolsRosterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tools/$slug' | '/tools/character-lookup' | '/tools/roster'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tools/$slug' | '/tools/character-lookup' | '/tools/roster'
  id:
    | '__root__'
    | '/'
    | '/tools/$slug'
    | '/tools/character-lookup'
    | '/tools/roster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsCharacterLookupRoute: typeof ToolsCharacterLookupRoute
  ToolsRosterRoute: typeof ToolsRosterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/roster': {
      id: '/tools/roster'
      path: '/tools/roster'
      fullPath: '/tools/roster'
      preLoaderRoute: typeof ToolsRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/character-lookup': {
      id: '/tools/character-lookup'
      path: '/tools/character-lookup'
      fullPath: '/tools/character-lookup'
      preLoaderRoute: typeof ToolsCharacterLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsCharacterLookupRoute: ToolsCharacterLookupRoute,
  ToolsRosterRoute: ToolsRosterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
